export const ADD_TO_DO = "ADD_TO_DO"
export const REMOVE_TO_DO = "REMOVE_TO_DO"
export const REPLACE_TO_DO = "REPLACE_TO_DO"
export const INIT_TO_DO_LIST = "INIT_TO_DO_LIST"
export const ADD_TAG = "ADD_TAG"
export const REMOVE_TAG = "REMOVE_TAG"
export const INIT_TAGS = "INIT_TAGS"